set(_CATKIN_CURRENT_PACKAGE "ekg_auv_testing")
set(ekg_auv_testing_VERSION "1.0.0")
set(ekg_auv_testing_MAINTAINER "Elinam Gbordzoe <egbordzo@purdue.edu>")
set(ekg_auv_testing_PACKAGE_FORMAT "2")
set(ekg_auv_testing_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "message_generation" "message_runtime" "caldus_description" "caracara_description" "smilodon_description" "teledyne_whn_dsl_description" "teledyne_whn_uuvsim_description" "teledyne_explorer4000_dsl_description" "teledyne_explorer4000_uuvsim_description" "nortek_dvl1000_4000_dsl_description" "nortek_dvl1000_4000_uuvsim_description" "uuv_assistants" "uuv_descriptions" "uuv_gazebo_plugins" "uuv_gazebo_ros_plugins" "ds_sim")
set(ekg_auv_testing_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "sensor_msgs" "std_msgs" "geometry_msgs" "caldus_description" "caracara_description" "smilodon_description" "teledyne_whn_dsl_description" "teledyne_whn_uuvsim_description" "teledyne_explorer4000_dsl_description" "teledyne_explorer4000_uuvsim_description" "nortek_dvl1000_4000_dsl_description" "nortek_dvl1000_4000_uuvsim_description" "uuv_assistants" "uuv_descriptions" "uuv_gazebo_plugins" "uuv_gazebo_ros_plugins" "ds_sim")
set(ekg_auv_testing_BUILDTOOL_DEPENDS "catkin")
set(ekg_auv_testing_BUILDTOOL_EXPORT_DEPENDS )
set(ekg_auv_testing_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "caldus_description" "caracara_description" "smilodon_description" "teledyne_whn_dsl_description" "teledyne_whn_uuvsim_description" "teledyne_explorer4000_dsl_description" "teledyne_explorer4000_uuvsim_description" "nortek_dvl1000_4000_dsl_description" "nortek_dvl1000_4000_uuvsim_description" "uuv_assistants" "uuv_descriptions" "uuv_gazebo_plugins" "uuv_gazebo_ros_plugins" "ds_sim")
set(ekg_auv_testing_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "caldus_description" "caracara_description" "smilodon_description" "teledyne_whn_dsl_description" "teledyne_whn_uuvsim_description" "teledyne_explorer4000_dsl_description" "teledyne_explorer4000_uuvsim_description" "nortek_dvl1000_4000_dsl_description" "nortek_dvl1000_4000_uuvsim_description" "uuv_assistants" "uuv_descriptions" "uuv_gazebo_plugins" "uuv_gazebo_ros_plugins" "ds_sim")
set(ekg_auv_testing_TEST_DEPENDS )
set(ekg_auv_testing_DOC_DEPENDS )
set(ekg_auv_testing_URL_WEBSITE "")
set(ekg_auv_testing_URL_BUGTRACKER "")
set(ekg_auv_testing_URL_REPOSITORY "")
set(ekg_auv_testing_DEPRECATED "")