// Generated by gencpp from file ekg_auv_testing/USBLResponseSim.msg
// DO NOT EDIT!


#ifndef EKG_AUV_TESTING_MESSAGE_USBLRESPONSESIM_H
#define EKG_AUV_TESTING_MESSAGE_USBLRESPONSESIM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ekg_auv_testing
{
template <class ContainerAllocator>
struct USBLResponseSim_
{
  typedef USBLResponseSim_<ContainerAllocator> Type;

  USBLResponseSim_()
    : transceiverID(0)
    , responseID(0)
    , transceiverModelName()
    , data()  {
    }
  USBLResponseSim_(const ContainerAllocator& _alloc)
    : transceiverID(0)
    , responseID(0)
    , transceiverModelName(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _transceiverID_type;
  _transceiverID_type transceiverID;

   typedef int32_t _responseID_type;
  _responseID_type responseID;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _transceiverModelName_type;
  _transceiverModelName_type transceiverModelName;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::ekg_auv_testing::USBLResponseSim_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ekg_auv_testing::USBLResponseSim_<ContainerAllocator> const> ConstPtr;

}; // struct USBLResponseSim_

typedef ::ekg_auv_testing::USBLResponseSim_<std::allocator<void> > USBLResponseSim;

typedef boost::shared_ptr< ::ekg_auv_testing::USBLResponseSim > USBLResponseSimPtr;
typedef boost::shared_ptr< ::ekg_auv_testing::USBLResponseSim const> USBLResponseSimConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ekg_auv_testing::USBLResponseSim_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ekg_auv_testing::USBLResponseSim_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ekg_auv_testing::USBLResponseSim_<ContainerAllocator1> & lhs, const ::ekg_auv_testing::USBLResponseSim_<ContainerAllocator2> & rhs)
{
  return lhs.transceiverID == rhs.transceiverID &&
    lhs.responseID == rhs.responseID &&
    lhs.transceiverModelName == rhs.transceiverModelName &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ekg_auv_testing::USBLResponseSim_<ContainerAllocator1> & lhs, const ::ekg_auv_testing::USBLResponseSim_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ekg_auv_testing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ekg_auv_testing::USBLResponseSim_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ekg_auv_testing::USBLResponseSim_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ekg_auv_testing::USBLResponseSim_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ekg_auv_testing::USBLResponseSim_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ekg_auv_testing::USBLResponseSim_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ekg_auv_testing::USBLResponseSim_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ekg_auv_testing::USBLResponseSim_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23b647a5a32e3bbb7ba751a1824c350f";
  }

  static const char* value(const ::ekg_auv_testing::USBLResponseSim_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23b647a5a32e3bbbULL;
  static const uint64_t static_value2 = 0x7ba751a1824c350fULL;
};

template<class ContainerAllocator>
struct DataType< ::ekg_auv_testing::USBLResponseSim_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ekg_auv_testing/USBLResponseSim";
  }

  static const char* value(const ::ekg_auv_testing::USBLResponseSim_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ekg_auv_testing::USBLResponseSim_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 transceiverID\n"
"int32 responseID\n"
"string transceiverModelName\n"
"string data\n"
;
  }

  static const char* value(const ::ekg_auv_testing::USBLResponseSim_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ekg_auv_testing::USBLResponseSim_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.transceiverID);
      stream.next(m.responseID);
      stream.next(m.transceiverModelName);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct USBLResponseSim_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ekg_auv_testing::USBLResponseSim_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ekg_auv_testing::USBLResponseSim_<ContainerAllocator>& v)
  {
    s << indent << "transceiverID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.transceiverID);
    s << indent << "responseID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.responseID);
    s << indent << "transceiverModelName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.transceiverModelName);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EKG_AUV_TESTING_MESSAGE_USBLRESPONSESIM_H
